# Generated by Django 6.0.2 on 2026-02-08 16:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='phone number is to be exactly 10 digits.', regex='^\\d{10}$')])),
                ('monthly_salary', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('approved_limit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('current_debt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('tenure', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('interest_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_repayment', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('emis_paid_on_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='loans.customer')),
            ],
        ),
    ]
